on:
  push:

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: feat/auto-update
      # Check out branch
      # Install aws
      # Install R (and packages)
      # Run refresher script
      - name: Refresh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
          AWS_DEFAULT_OUTPUT: json
        run: aws s3 rw-research-team cp s3://ethswarm-research-team/data-test2.rds data-test2.rds
