on:
  push:

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      # Check out branch
      # Install aws
      # Install R (and packages)
      # Run refresher script
      - uses: actions/checkout@v3
        with:
          ref: feat/auto-update
      - run: ls -a
