on:
  push:

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: feat/auto-update
      # Check out branch
      # Install aws
      # Install R (and packages)
      # Run refresher script
      - name: list
        run: aws --version
